export default [
  { id: 'AFN', label: 'Afghan afghani' },
  { id: 'ALL', label: 'Albanian lek' },
  { id: 'DZD', label: 'Algerian dinar' },
  { id: 'AOA', label: 'Angolan kwanza' },
  { id: 'ARS', label: 'Argentine peso' },
  { id: 'AMD', label: 'Armenian dram' },
  { id: 'AWG', label: 'Aruban guilder' },
  { id: 'AUD', label: 'Australian dollar' },
  { id: 'AZN', label: 'Azerbaijanian new manat' },
  { id: 'BSD', label: 'Bahamian dollar' },
  { id: 'BHD', label: 'Bahraini dinar' },
  { id: 'BDT', label: 'Bangladeshi taka' },
  { id: 'BBD', label: 'Barbados dollar' },
  { id: 'BYN', label: 'Belarusian ruble' },
  { id: 'BYR', label: 'Belarusian ruble' },
  { id: 'BZD', label: 'Belize dollar' },
  { id: 'BMD', label: 'Bermudian dollar' },
  { id: 'BTN', label: 'Bhutan ngultrum' },
  { id: 'BOB', label: 'Bolivian boliviano' },
  { id: 'BWP', label: 'Botswana pula' },
  { id: 'BRL', label: 'Brazilian real' },
  { id: 'GBP', label: 'British pound' },
  { id: 'BND', label: 'Brunei dollar' },
  { id: 'BGN', label: 'Bulgarian lev' },
  { id: 'BIF', label: 'Burundi franc' },
  { id: 'XOF', label: 'CFA franc BCEAO' },
  { id: 'XAF', label: 'CFA franc BEAC' },
  { id: 'XPF', label: 'CFP franc' },
  { id: 'KHR', label: 'Cambodian riel' },
  { id: 'CAD', label: 'Canadian dollar' },
  { id: 'CVE', label: 'Cape Verde escudo' },
  { id: 'KYD', label: 'Cayman Islands dollar' },
  { id: 'CLP', label: 'Chilean peso' },
  { id: 'CNY', label: 'Chinese yuan renminbi' },
  { id: 'COP', label: 'Colombian peso' },
  { id: 'KMF', label: 'Comoros franc' },
  { id: 'CDF', label: 'Congolese franc' },
  { id: 'CRC', label: 'Costa Rican colon' },
  { id: 'HRK', label: 'Croatian kuna' },
  { id: 'CUP', label: 'Cuban peso' },
  { id: 'CZK', label: 'Czech koruna' },
  { id: 'DKK', label: 'Danish krone' },
  { id: 'DJF', label: 'Djibouti franc' },
  { id: 'DOP', label: 'Dominican peso' },
  { id: 'EUR', label: 'EU euro' },
  { id: 'XCD', label: 'East Caribbean dollar' },
  { id: 'EGP', label: 'Egyptian pound' },
  { id: 'SVC', label: 'El Salvador colon' },
  { id: 'ERN', label: 'Eritrean nakfa' },
  { id: 'ETB', label: 'Ethiopian birr' },
  { id: 'FKP', label: 'Falkland Islands pound' },
  { id: 'FJD', label: 'Fiji dollar' },
  { id: 'GMD', label: 'Gambian dalasi' },
  { id: 'GEL', label: 'Georgian lari' },
  { id: 'GHS', label: 'Ghanaian new cedi' },
  { id: 'GIP', label: 'Gibraltar pound' },
  { id: 'GTQ', label: 'Guatemalan quetzal' },
  { id: 'GNF', label: 'Guinean franc' },
  { id: 'GYD', label: 'Guyana dollar' },
  { id: 'HTG', label: 'Haitian gourde' },
  { id: 'HNL', label: 'Honduran lempira' },
  { id: 'HKD', label: 'Hong Kong SAR dollar' },
  { id: 'HUF', label: 'Hungarian forint' },
  { id: 'XDR', label: 'IMF special drawing right' },
  { id: 'ISK', label: 'Icelandic krona' },
  { id: 'INR', label: 'Indian rupee' },
  { id: 'IDR', label: 'Indonesian rupiah' },
  { id: 'IRR', label: 'Iranian rial' },
  { id: 'IQD', label: 'Iraqi dinar' },
  { id: 'ILS', label: 'Israeli new shekel' },
  { id: 'JMD', label: 'Jamaican dollar' },
  { id: 'JPY', label: 'Japanese yen' },
  { id: 'JOD', label: 'Jordanian dinar' },
  { id: 'KZT', label: 'Kazakh tenge' },
  { id: 'KES', label: 'Kenyan shilling' },
  { id: 'KWD', label: 'Kuwaiti dinar' },
  { id: 'KGS', label: 'Kyrgyz som' },
  { id: 'LAK', label: 'Lao kip' },
  { id: 'LVL', label: 'Latvian lats' },
  { id: 'LBP', label: 'Lebanese pound' },
  { id: 'LSL', label: 'Lesotho loti' },
  { id: 'LRD', label: 'Liberian dollar' },
  { id: 'LYD', label: 'Libyan dinar' },
  { id: 'LTL', label: 'Lithuanian litas' },
  { id: 'MOP', label: 'Macao SAR pataca' },
  { id: 'MKD', label: 'Macedonian denar' },
  { id: 'MGA', label: 'Malagasy ariary' },
  { id: 'MWK', label: 'Malawi kwacha' },
  { id: 'MYR', label: 'Malaysian ringgit' },
  { id: 'MVR', label: 'Maldivian rufiyaa' },
  { id: 'MRO', label: 'Mauritanian ouguiya' },
  { id: 'MUR', label: 'Mauritius rupee' },
  { id: 'MXN', label: 'Mexican peso' },
  { id: 'MDL', label: 'Moldovan leu' },
  { id: 'MNT', label: 'Mongolian tugrik' },
  { id: 'MAD', label: 'Moroccan dirham' },
  { id: 'MZN', label: 'Mozambique new metical' },
  { id: 'MMK', label: 'Myanmar kyat' },
  { id: 'NAD', label: 'Namibian dollar' },
  { id: 'NPR', label: 'Nepalese rupee' },
  { id: 'ANG', label: 'Netherlands Antillian guilder' },
  { id: 'NZD', label: 'New Zealand dollar' },
  { id: 'NIO', label: 'Nicaraguan cordoba oro' },
  { id: 'NGN', label: 'Nigerian naira' },
  { id: 'KPW', label: 'North Korean won' },
  { id: 'NOK', label: 'Norwegian krone' },
  { id: 'OMR', label: 'Omani rial' },
  { id: 'PKR', label: 'Pakistani rupee' },
  { id: 'PAB', label: 'Panamanian balboa' },
  { id: 'PGK', label: 'Papua New Guinea kina' },
  { id: 'PYG', label: 'Paraguayan guarani' },
  { id: 'PEN', label: 'Peruvian nuevo sol' },
  { id: 'PHP', label: 'Philippine peso' },
  { id: 'PLN', label: 'Polish zloty' },
  { id: 'QAR', label: 'Qatari rial' },
  { id: 'RON', label: 'Romanian new leu' },
  { id: 'RUB', label: 'Russian ruble' },
  { id: 'RWF', label: 'Rwandan franc' },
  { id: 'SHP', label: 'Saint Helena pound' },
  { id: 'WST', label: 'Samoan tala' },
  { id: 'STD', label: 'Sao Tome and Principe dobra' },
  { id: 'SAR', label: 'Saudi riyal' },
  { id: 'RSD', label: 'Serbian dinar' },
  { id: 'SCR', label: 'Seychelles rupee' },
  { id: 'SLL', label: 'Sierra Leone leone' },
  { id: 'XAG', label: 'Silver (ounce)' },
  { id: 'SGD', label: 'Singapore dollar' },
  { id: 'SBD', label: 'Solomon Islands dollar' },
  { id: 'SOS', label: 'Somali shilling' },
  { id: 'ZAR', label: 'South African rand' },
  { id: 'KRW', label: 'South Korean won' },
  { id: 'LKR', label: 'Sri Lanka rupee' },
  { id: 'SDG', label: 'Sudanese pound' },
  { id: 'SRD', label: 'Suriname dollar' },
  { id: 'SZL', label: 'Swaziland lilangeni' },
  { id: 'SEK', label: 'Swedish krona' },
  { id: 'CHF', label: 'Swiss franc' },
  { id: 'SYP', label: 'Syrian pound' },
  { id: 'TWD', label: 'Taiwan New dollar' },
  { id: 'TJS', label: 'Tajik somoni' },
  { id: 'TZS', label: 'Tanzanian shilling' },
  { id: 'THB', label: 'Thai baht' },
  { id: 'TOP', label: "Tongan pa'anga" },
  { id: 'TTD', label: 'Trinidad and Tobago dollar' },
  { id: 'TND', label: 'Tunisian dinar' },
  { id: 'TRY', label: 'Turkish lira' },
  { id: 'TMT', label: 'Turkmen new manat' },
  { id: 'AED', label: 'UAE dirham' },
  { id: 'USD', label: 'US dollar' },
  { id: 'UGX', label: 'Uganda new shilling' },
  { id: 'UAH', label: 'Ukrainian hryvnia' },
  { id: 'UYU', label: 'Uruguayan peso uruguayo' },
  { id: 'UZS', label: 'Uzbekistani sum' },
  { id: 'VUV', label: 'Vanuatu vatu' },
  { id: 'VEF', label: 'Venezuelan bolivar fuerte' },
  { id: 'VND', label: 'Vietnamese dong' },
  { id: 'YER', label: 'Yemeni rial' },
  { id: 'ZMK', label: 'Zambian kwacha' },
  { id: 'ZMW', label: 'Zambian kwacha' },
  { id: 'ZWL', label: 'Zimbabwe dollar' },
];
